language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libow-dev
install:
  - pip install --upgrade pytest pytest-mock pytest-cov coveralls codecov
  - pip install -r dev-requirements.txt
  - pip install -e .
script:
  - pytest --cov-config .coveragerc --cov=labgrid
  - python setup.py build_sphinx
  - make -C man all
  - git diff
  - git diff-index --quiet HEAD --
after_success:
  - coveralls
  - codecov
