language: python
dist: bionic
addons:
  apt:
    packages:
      libow-dev
      openssh-server
      openssh-client

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - ssh-keygen -f ~/.ssh/id_ed25519.local -t ed25519 -N ""
  - cat ~/.ssh/id_ed25519.local.pub > ~/.ssh/authorized_keys
  - echo -e "Host localhost ip6-localhost\n  Hostname 127.0.0.1\n  IdentityFile ~/.ssh/id_ed25519.local\n  UserKnownHostsFile ~/.ssh/known_hosts.local" > ~/.ssh/config
  - ssh -o StrictHostKeyChecking=no localhost echo OK
install:
  - pip install -r travis-requirements.txt
  - sudo mkdir /var/cache/labgrid && sudo chmod 1775 /var/cache/labgrid && sudo chown root:travis /var/cache/labgrid
script:
  - pip install -e .
  - pytest --cov-config .coveragerc --cov=labgrid --local-sshmanager
  - python setup.py build_sphinx
  - make -C man all
  - git --no-pager diff --exit-code
after_success:
  - codecov

matrix:
  include:
    - stage: docker
      services:
        - docker
      script:
        - ./docker/build.sh
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ] && [ "$DOCKER_USERNAME" != "" ] && [ "$DOCKER_TOKEN" != "" ]; then
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin;
          docker images;
          docker tag labgrid-client labgrid/client;
          docker tag labgrid-exporter labgrid/exporter;
          docker tag labgrid-coordinator labgrid/coordinator;
          docker push labgrid/client;
          docker push labgrid/exporter;
          docker push labgrid/coordinator;
          fi
    - stage: optional
      python: "nightly"
  allow_failures:
    - stage: optional
