version: 2
workers:
- type: router
  realms:
  - name: realm1
    roles:
    - name: authenticator
      permissions:
      - uri: org.labgrid.authenticate
        match: exact
        allow:
          call: false
          register: true
          publish: false
          subscribe: false
        disclose:
          caller: false
          publisher: false
        cache: true
    - name: public
      permissions:
      - uri: ''
        match: prefix
        allow:
          call: true
          register: true
          publish: true
          subscribe: true
        disclose:
          caller: true
          publisher: true
        cache: true
  transports:
  - type: web
    endpoint:
      type: tcp
      port: 20408
    paths:
      /:
        type: static
        directory: ../web
      ws:
        type: websocket
        auth:
          ticket:
            type: dynamic
            authenticator: org.labgrid.authenticate
  components:
  - type: class
    classname: labgrid.remote.authenticator.AuthenticatorSession
    realm: realm1
    role: authenticator
- id: coordinator
  type: guest
  executable: python3
  arguments:
  - -mlabgrid.remote.coordinator
  options:
    workdir: .
    env:
      vars:
        WS: ws://localhost:20408/ws
