name: unit tests

on: [push, pull_request, workflow_dispatch]

jobs:
  push-pr-unit-tests:
    name: unit tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      python-version: ${{ matrix.python-version }}
  push-pr-unit-tests-docker:
    name: Docker Unit Tests
    uses: ./.github/workflows/reusable-unit-tests-docker.yml
  build-and-release:
    name: Release to Pypi
    needs: push-pr-unit-tests
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    uses: ./.github/workflows/build-and-release.yml
